version: '3'
services:
  ## the develop work image with lib dependencies
  dev-image:
    build: ./dev
    image: iiparra/dev-cpp-work
    ports:
      - "2000:2000"
      - "50010:50010"
    privileged: true
    container_name: devenv
# mapping your project folder (.) to /home/develop/project    
    volumes:
      - "./:/home/develop/project"
